import type { Lesson } from "./types"

const mockData: Lesson[] = [
  {
    id: "mock-001",
    slug: "mock-001",
    title: "Scientists Discover New Deep-Sea Species",
    topic: "Science",
    levelMin: 4,
    levelMax: 5,
    cefr: "B2",
    difficulty: "harder",
    publishedAt: "2026-06-01",
    activityCount: 40,
    url: "https://breakingnewsenglish.com",
  },
  {
    id: "mock-002",
    slug: "mock-002",
    title: "World Leaders Meet on Climate Change",
    topic: "Environment",
    levelMin: 0,
    levelMax: 2,
    cefr: "A1",
    difficulty: "easier",
    publishedAt: "2026-05-28",
    activityCount: 27,
    url: "https://breakingnewsenglish.com",
  },
  {
    id: "mock-003",
    slug: "mock-003",
    title: "Tech Giants Face New Regulations",
    topic: "Technology",
    levelMin: 4,
    levelMax: 5,
    cefr: "B2",
    difficulty: "harder",
    publishedAt: "2026-05-25",
    activityCount: 40,
    url: "https://breakingnewsenglish.com",
  },
  {
    id: "mock-004",
    slug: "mock-004",
    title: "New Study on Sleep and Memory",
    topic: "Health",
    levelMin: 1,
    levelMax: 2,
    cefr: "A2",
    difficulty: "easier",
    publishedAt: "2026-05-20",
    activityCount: 27,
    url: "https://breakingnewsenglish.com",
  },
  {
    id: "mock-005",
    slug: "mock-005",
    title: "Global Economy Shows Signs of Recovery",
    topic: "Business",
    levelMin: 4,
    levelMax: 5,
    cefr: "B2",
    difficulty: "harder",
    publishedAt: "2026-05-15",
    activityCount: 40,
    url: "https://breakingnewsenglish.com",
  },
  {
    id: "mock-006",
    slug: "mock-006",
    title: "Schools Introduce AI Tutors for Students",
    topic: "Education",
    levelMin: 0,
    levelMax: 2,
    cefr: "A1",
    difficulty: "easier",
    publishedAt: "2026-05-10",
    activityCount: 27,
    url: "https://breakingnewsenglish.com",
  },
  {
    id: "mock-007",
    slug: "mock-007",
    title: "Astronauts Return from Record Space Mission",
    topic: "Science",
    levelMin: 4,
    levelMax: 5,
    cefr: "B2",
    difficulty: "harder",
    publishedAt: "2026-05-05",
    activityCount: 40,
    url: "https://breakingnewsenglish.com",
  },
  {
    id: "mock-008",
    slug: "mock-008",
    title: "Social Media Trends Among Teenagers",
    topic: "Lifestyle",
    levelMin: 1,
    levelMax: 2,
    cefr: "A2",
    difficulty: "easier",
    publishedAt: "2026-04-30",
    activityCount: 27,
    url: "https://breakingnewsenglish.com",
  },
  {
    id: "mock-009",
    slug: "mock-009",
    title: "Famous Author Wins Prestigious Prize",
    topic: "People",
    levelMin: 4,
    levelMax: 5,
    cefr: "B2",
    difficulty: "harder",
    publishedAt: "2026-04-25",
    activityCount: 40,
    url: "https://breakingnewsenglish.com",
  },
]

export default mockData
